project:
  type: website

website:
  title: "Leeutjie"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/leeutjie?tab=repositories
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: spacelab
    css: styles.css
    
execute:
  freeze: auto

